export const SNAPSHOT = {
	GET_SNAPSHOT_SUCCESS: 'GET_SNAPSHOT_SUCCESS',
	GET_SNAPSHOT_ERROR: 'GET_SNAPSHOT_ERROR',
	GET_SNAPSHOT: 'GET_SNAPSHOT',
	SET_CURRENCY: 'SET_CURRENCY',
}

export const SOCKET = {
	SOCKET_CONNECTION_INIT: 'SOCKET_CONNECTION_INIT',
	SOCKET_CONNECTION_SUCCESS: 'SOCKET_CONNECTION_SUCCESS',
	SOCKET_CONNECTION_ERROR: 'SOCKET_CONNECTION_ERROR',
	SOCKET_CONNECTION_CLOSED: 'SOCKET_CONNECTION_CLOSED',
	SOCKET_MESSAGE: 'SOCKET_MESSAGE',
}